version: '3.8'
services:
  traefik:
    restart: always
    image: traefik:latest
    container_name: traefik-netbird
    ports:
      - '8080:80'
      - '8443:443'
    environment:
      - CF_DNS_API_TOKEN=xxx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/traefik.toml:/etc/traefik/traefik.toml
      - ./data/services.toml:/etc/traefik/services.toml
      - ./data/acme.json:/acme.json
    networks:
      - traefik
    labels:
      - 'traefik.http.middlewares.redirection.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.redirection.redirectscheme.permanent=true'
      
networks:
  traefik:
